[package]
name = "playgraph-core"
description = "Data model and code generation for rust-playgraph"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
syn.workspace = true
quote.workspace = true
proc-macro2.workspace = true
thiserror.workspace = true
prettyplease.workspace = true
